name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get next version
        uses: reecetech/version-increment@2021.10.5
        id: version
        with:
          scheme: semver
          increment: patch
      
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.amosgross.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t registry.amosgross.com/getcaked:${{ steps.version.outputs.version }} -f ./deployment/Dockerfile .
      - name: Push Docker Image
        run: docker push registry.amosgross.com/getcaked:${{ steps.version.outputs.version }}

      - name: Kube Update Image
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.KUBE_CONFIG_DATA }}
          args: -n getcaked set image deployment/getcaked getcaked=registry.amosgross.com/getcaked:${{ steps.version.outputs.version }}
          
      - name: Create new Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: ${{ steps.version.outputs.version }}
          prerelease: false
           
      - name:  'Bump Version frontend'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PACKAGEJSON_DIR:  'frontend'
        with:
          default: patch
          skip-tag:  'true'
          
      - name:  'Bump Version backend'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PACKAGEJSON_DIR:  'backend'
        with:
          skip-tag:  'true'
          default: patch
          minor-wording:  ''
          major-wording:  ''
          patch-wording:  '' 
          commit-message: 'ci: version change to {{version}} [skip ci]'
