name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get next version
        uses: reecetech/version-increment@2021.10.4
        id: version
        with:
          scheme: semver
          increment: patch
      
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.amosgross.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t registry.amosgross.com/getcaked:${{ steps.version.outputs.version }} .
      - name: Push Docker Image
        run: docker push registry.amosgross.com/getcaked:${{ steps.version.outputs.version }}

      - name: Kube Update Image
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.KUBE_CONFIG_DATA }}
          args: -n homepage set image deployment/getcaked homepage=registry.amosgross.com/getcaked:${{ steps.version.outputs.version }}
          
      - name: Create new Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.version.outputs.version }}
          prerelease: false
